// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH feed_follows_ins AS (
  INSERT INTO feed_follows(id, created_at, updated_at, user_id, feed_id)
  VALUES ($1, $2, $3, $4, $5)
  RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT feed_follows_ins.id, feed_follows_ins.created_at, feed_follows_ins.updated_at, feed_follows_ins.user_id, feed_follows_ins.feed_id,
  feeds.name AS feed_name,
  users.name AS user_name
FROM feed_follows_ins
INNER JOIN feeds
ON feeds.id = feed_follows_ins.feed_id
INNER JOIN users
ON users.id = feed_follows_ins.user_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const getUserFeeds = `-- name: GetUserFeeds :many
SELECT
  feeds.name AS feed_name,
  feeds.url,
  feed_follows.updated_at
FROM users
INNER JOIN feed_follows
ON feed_follows.user_id = users.id
INNER JOIN feeds
ON feeds.id = feed_follows.feed_id
WHERE users.name = $1
`

type GetUserFeedsRow struct {
	FeedName  string
	Url       string
	UpdatedAt time.Time
}

func (q *Queries) GetUserFeeds(ctx context.Context, name string) ([]GetUserFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedsRow
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(&i.FeedName, &i.Url, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
